import { Zap, Sparkles, Rocket, Heart, Activity, Brain, Crown, Moon, Shield, Dumbbell, Flame, Target, RefreshCw, Leaf, Pill, Eye, Sun, Wind, Crosshair, LucideIcon } from "lucide-react";
import { getSystemColor } from "@/data/body-systems";

export interface KnownStack {
  name: string;
  peptides: string[];
  icon: LucideIcon;
  color: string;
  description: string;
  synergyBonus: number;
  detailPageId?: string;
}

export interface PeptidePathway {
  name: string;
  pathways: string[];
  mechanisms: string[];
  systems: string[];
}

export const KNOWN_STACKS: KnownStack[] = [
  {
    name: "Wolverine Stack",
    peptides: ["bpc-157", "tb-500"],
    icon: Zap,
    color: getSystemColor("healing")!,
    description: "BPC-157 drives local repair via VEGF upregulation while TB-500 provides systemic healing through thymosin beta-4 actin regulation \u2014 covering both localized and whole-body regeneration",
    synergyBonus: 95,
  },
  {
    name: "Total Regen",
    peptides: ["bpc-157", "tb-500", "ipamorelin"],
    icon: Shield,
    color: getSystemColor("healing")!,
    description: "Local VEGF-driven healing + systemic thymosin repair + selective GH/IGF-1 amplification for comprehensive tissue regeneration",
    synergyBonus: 92,
  },
  {
    name: "Gut Restore",
    peptides: ["bpc-157", "kpv"],
    icon: Pill,
    color: getSystemColor("gut")!,
    description: "BPC-157 repairs gut mucosal lining through cytoprotection while KPV inhibits NF-\u03BAB inflammatory cascades \u2014 structural repair + inflammation suppression",
    synergyBonus: 91,
  },
  {
    name: "Glow Protocol",
    peptides: ["bpc-157", "tb-500", "ghk-cu"],
    icon: Sparkles,
    color: getSystemColor("skin")!,
    description: "Copper-peptide collagen synthesis + thymosin vascular repair + VEGF-driven angiogenesis for multi-layer skin regeneration",
    synergyBonus: 90,
  },
  {
    name: "GH Amplifier",
    peptides: ["ipamorelin", "cjc-1295"],
    icon: Rocket,
    color: getSystemColor("growth")!,
    description: "Pituitary GHRP + hypothalamic GHRH dual-axis stimulation \u2014 the gold-standard GH amplification protocol producing synergistic output far greater than either alone",
    synergyBonus: 88,
  },
  {
    name: "Lean Mass",
    peptides: ["cjc-1295", "ipamorelin", "mots-c"],
    icon: Dumbbell,
    color: getSystemColor("growth")!,
    description: "Dual-axis GH amplification + AMPK-driven mitochondrial energy production for body composition optimization",
    synergyBonus: 87,
  },
  {
    name: "Cognitive Edge",
    peptides: ["semax", "selank"],
    icon: Brain,
    color: getSystemColor("cognitive")!,
    description: "Gold-standard nootropic pairing \u2014 BDNF/NGF cognitive enhancement + GABAergic anxiolytic modulation for calm, focused performance",
    synergyBonus: 86,
  },
  {
    name: "Anti-Aging Protocol",
    peptides: ["epithalon", "ghk-cu", "ipamorelin"],
    icon: Leaf,
    color: getSystemColor("longevity")!,
    description: "Telomerase activation + DNA repair gene expression + GH-driven tissue renewal \u2014 three complementary anti-aging mechanisms",
    synergyBonus: 85,
  },
  {
    name: "Longevity Protocol",
    peptides: ["epithalon", "ghk-cu"],
    icon: Crown,
    color: getSystemColor("longevity")!,
    description: "Epithalon activates telomerase for cellular longevity while GHK-Cu activates DNA repair genes and collagen turnover \u2014 both address aging at the cellular level",
    synergyBonus: 84,
  },
  {
    name: "Deep Sleep Formula",
    peptides: ["dsip", "ipamorelin", "epithalon"],
    icon: Moon,
    color: getSystemColor("sleep")!,
    description: "Delta sleep induction + sleep-phase GH release + pineal melatonin regulation \u2014 optimizing the nighttime regeneration window",
    synergyBonus: 84,
  },
  {
    name: "Fat Burner Stack",
    peptides: ["tesamorelin", "cjc-1295", "mots-c"],
    icon: Flame,
    color: getSystemColor("metabolic")!,
    description: "Targeted fat reduction + GH elevation + metabolic acceleration",
    synergyBonus: 83,
  },
  {
    name: "Recovery+",
    peptides: ["bpc-157", "ghk-cu"],
    icon: Heart,
    color: getSystemColor("healing")!,
    description: "GHK-Cu drives copper-dependent collagen and elastin synthesis while BPC-157 provides the vascular infrastructure for nutrient delivery to remodeling tissue",
    synergyBonus: 82,
  },
  {
    name: "Performance Stack",
    peptides: ["cjc-1295", "ipamorelin", "bpc-157"],
    icon: Target,
    color: getSystemColor("growth")!,
    description: "GH optimization + tissue protection for athletic performance",
    synergyBonus: 81,
  },
  {
    name: "Energy Stack",
    peptides: ["mots-c", "rr-a3"],
    icon: Activity,
    color: getSystemColor("metabolic")!,
    description: "Mitochondrial power + metabolic signaling",
    synergyBonus: 80,
  },
  {
    name: "Immune Boost",
    peptides: ["thymalin", "selank", "kpv"],
    icon: RefreshCw,
    color: getSystemColor("immune")!,
    description: "Thymus support + immune modulation + anti-inflammatory",
    synergyBonus: 79,
  },
  {
    name: "Metabolic Reset",
    peptides: ["rr-a3", "bpc-157"],
    icon: RefreshCw,
    color: getSystemColor("metabolic")!,
    description: "Triple metabolic receptor agonism + gut cytoprotection — BPC-157 supports GI comfort during metabolic compound research",
    synergyBonus: 88,
  },
  {
    name: "Dual Metabolic",
    peptides: ["rr-a3", "aod-9604"],
    icon: Flame,
    color: getSystemColor("metabolic")!,
    description: "Triple metabolic receptor agonist + targeted lipolysis fragment",
    synergyBonus: 85,
  },
  {
    name: "Metabolic Optimizer",
    peptides: ["rr-a3", "tesamorelin"],
    icon: Target,
    color: getSystemColor("metabolic")!,
    description: "Triple receptor metabolic control + visceral fat-targeting GHRH analog",
    synergyBonus: 84,
  },
  {
    name: "Fat Metabolism Pro",
    peptides: ["aod-9604", "mots-c"],
    icon: Flame,
    color: getSystemColor("metabolic")!,
    description: "HGH fragment lipolysis + AMPK-driven mitochondrial fat oxidation",
    synergyBonus: 83,
  },
  {
    name: "Cognitive Powerhouse",
    peptides: ["cerebrolysin", "semax", "selank"],
    icon: Brain,
    color: getSystemColor("cognitive")!,
    description: "Multi-peptide neurotrophic mix + targeted BDNF/NGF stimulation + GABAergic mood stabilization \u2014 triple-layered brain support",
    synergyBonus: 90,
  },
  {
    name: "Muscle Growth Stack",
    peptides: ["igf-1-lr3", "mgf"],
    icon: Dumbbell,
    color: getSystemColor("growth")!,
    description: "Systemic IGF-1 signaling + localized mechano growth factor for hypertrophy",
    synergyBonus: 87,
  },
  {
    name: "Immune Defense",
    peptides: ["ll-37", "thymalin"],
    icon: Shield,
    color: getSystemColor("immune")!,
    description: "LL-37 cathelicidin provides innate antimicrobial defense while Thymalin restores adaptive immunity through thymic T-cell regeneration",
    synergyBonus: 85,
  },
  {
    name: "Desire Protocol",
    peptides: ["melanotan-ii", "pt-141"],
    icon: Heart,
    color: getSystemColor("mood")!,
    description: "Melanocortin receptor activation for libido + arousal enhancement",
    synergyBonus: 86,
  },
  {
    name: "Mitochondrial Stack",
    peptides: ["ss-31", "mots-c"],
    icon: Zap,
    color: getSystemColor("energy")!,
    description: "SS-31 stabilizes cardiolipin in mitochondrial membranes, then MOTS-C activates AMPK for new mitochondrial biogenesis \u2014 sequential: prime existing, then build new",
    synergyBonus: 88,
  },
  {
    name: "Anti-Wrinkle Complex",
    peptides: ["snap-8", "ghk-cu"],
    icon: Sparkles,
    color: getSystemColor("skin")!,
    description: "Neuromuscular relaxation + copper-peptide collagen remodeling",
    synergyBonus: 83,
  },
  {
    name: "GH Secretagogue Duo",
    peptides: ["ghrp-2", "cjc-1295"],
    icon: Rocket,
    color: getSystemColor("growth")!,
    description: "Potent GH release peptide + sustained GHRH for amplified growth hormone",
    synergyBonus: 87,
  },
  {
    name: "GH Pulse Stack",
    peptides: ["ghrp-6", "sermorelin"],
    icon: Rocket,
    color: getSystemColor("growth")!,
    description: "Hunger-stimulating GH release + natural GHRH analog for deep GH pulses",
    synergyBonus: 85,
  },
  {
    name: "Sermorelin Amplifier",
    peptides: ["sermorelin", "ipamorelin"],
    icon: Zap,
    color: getSystemColor("growth")!,
    description: "GHRH analog + selective GHRP for clean growth hormone elevation",
    synergyBonus: 86,
  },
  {
    name: "Triple GH Protocol",
    peptides: ["sermorelin", "ghrp-2", "ipamorelin"],
    icon: Crown,
    color: getSystemColor("growth")!,
    description: "GHRH base + dual GHRP synergy for maximum natural GH output",
    synergyBonus: 89,
  },
  {
    name: "Neuroprotective Stack",
    peptides: ["cerebrolysin", "pinealon"],
    icon: Brain,
    color: getSystemColor("cognitive")!,
    description: "Neurotrophic peptide mix + pineal-derived neuroprotection",
    synergyBonus: 84,
  },
  {
    name: "Advanced Nootropic",
    peptides: ["semax", "cerebrolysin"],
    icon: Eye,
    color: getSystemColor("cognitive")!,
    description: "BDNF/NGF stimulation + multi-peptide neurotrophic support",
    synergyBonus: 85,
  },
  {
    name: "Fertility Support",
    peptides: ["kisspeptin-10", "gonadorelin"],
    icon: Heart,
    color: getSystemColor("hormonal")!,
    description: "Kisspeptin GnRH triggering + direct GnRH pulsatile stimulation",
    synergyBonus: 85,
  },
  {
    name: "Weight Management Pro",
    peptides: ["cagrilintide", "rr-a3"],
    icon: Target,
    color: getSystemColor("metabolic")!,
    description: "Amylin analog appetite control + triple metabolic receptor agonist",
    synergyBonus: 88,
  },
  {
    name: "Metabolic Duo",
    peptides: ["mazdutide", "bpc-157"],
    icon: Pill,
    color: getSystemColor("metabolic")!,
    description: "Dual metabolic receptor agonist + gut protective healing peptide",
    synergyBonus: 83,
  },
  {
    name: "Survodutide Stack",
    peptides: ["survodutide", "aod-9604"],
    icon: Flame,
    color: getSystemColor("metabolic")!,
    description: "Dual metabolic receptor agonist + HGH fragment for body composition",
    synergyBonus: 82,
  },
  {
    name: "Weight Loss Trio",
    peptides: ["survodutide", "5-amino-1mq", "mots-c"],
    icon: Activity,
    color: getSystemColor("metabolic")!,
    description: "Incretin signaling + NNMT inhibition + mitochondrial metabolism",
    synergyBonus: 85,
  },
  {
    name: "NNMT Metabolic",
    peptides: ["5-amino-1mq", "aod-9604"],
    icon: Crosshair,
    color: getSystemColor("metabolic")!,
    description: "NNMT enzyme inhibition + GH fragment lipolysis for fat cell targeting",
    synergyBonus: 81,
  },
  {
    name: "Myostatin Block",
    peptides: ["ace-031", "igf-1-lr3"],
    icon: Dumbbell,
    color: getSystemColor("growth")!,
    description: "ActRIIB decoy receptor + IGF-1 for muscle growth beyond natural limits",
    synergyBonus: 86,
  },
  {
    name: "Muscle Builder Pro",
    peptides: ["ace-031", "mgf", "peg-mgf"],
    icon: Dumbbell,
    color: getSystemColor("growth")!,
    description: "Myostatin inhibition + local + extended mechano growth factors",
    synergyBonus: 85,
  },
  {
    name: "Exercise Mimetic",
    peptides: ["aicar", "slu-pp-332"],
    icon: Activity,
    color: getSystemColor("metabolic")!,
    description: "AMPK activation + REV-ERB agonism for exercise-pathway mimicry",
    synergyBonus: 84,
  },
  {
    name: "Endurance Stack",
    peptides: ["aicar", "mots-c", "ss-31"],
    icon: Wind,
    color: getSystemColor("energy")!,
    description: "Triple metabolic boost - AMPK + mitochondrial biogenesis + cardiolipin",
    synergyBonus: 87,
  },
  {
    name: "Vascular Fat Loss",
    peptides: ["adipotide", "aod-9604"],
    icon: Crosshair,
    color: getSystemColor("metabolic")!,
    description: "Fat vasculature targeting + HGH fragment lipolysis",
    synergyBonus: 80,
  },
  {
    name: "Immune Sentinel",
    peptides: ["ll-37", "thymosin-alpha-1"],
    icon: Shield,
    color: getSystemColor("immune")!,
    description: "Cathelicidin antimicrobial + thymic immune cell activation",
    synergyBonus: 87,
  },
  {
    name: "Full Immune Protocol",
    peptides: ["thymosin-alpha-1", "thymalin", "kpv"],
    icon: Shield,
    color: getSystemColor("immune")!,
    description: "Thymosin immune activation + thymic regeneration + anti-inflammatory",
    synergyBonus: 86,
  },
  {
    name: "Gut Immune Shield",
    peptides: ["ll-37", "kpv", "bpc-157"],
    icon: Pill,
    color: getSystemColor("gut")!,
    description: "Antimicrobial defense + gut anti-inflammatory + mucosal healing",
    synergyBonus: 88,
  },
  {
    name: "Senolytic Protocol",
    peptides: ["foxo4-dri", "epithalon"],
    icon: Leaf,
    color: getSystemColor("longevity")!,
    description: "Senescent cell clearance + telomerase activation for cellular renewal",
    synergyBonus: 84,
  },
  {
    name: "Antioxidant Defense",
    peptides: ["glutathione", "ss-31"],
    icon: Shield,
    color: getSystemColor("immune")!,
    description: "Master antioxidant + mitochondrial membrane protection",
    synergyBonus: 83,
  },
  {
    name: "Detox & Longevity",
    peptides: ["glutathione", "epithalon", "ghk-cu"],
    icon: Leaf,
    color: getSystemColor("longevity")!,
    description: "Cellular detoxification + telomere support + tissue remodeling",
    synergyBonus: 82,
  },
  {
    name: "Tanning & Libido",
    peptides: ["melanotan-ii", "melanotan-i"],
    icon: Sun,
    color: getSystemColor("skin")!,
    description: "MC1R activation duo - broad + selective melanocortin stimulation",
    synergyBonus: 80,
  },
  {
    name: "Skin Pigmentation",
    peptides: ["melanotan-i", "ghk-cu"],
    icon: Sun,
    color: getSystemColor("skin")!,
    description: "Selective melanogenesis + copper-peptide skin remodeling",
    synergyBonus: 78,
  },
  {
    name: "Oxytocin Mood",
    peptides: ["oxytocin", "selank"],
    icon: Heart,
    color: getSystemColor("mood")!,
    description: "Social bonding hormone + anxiolytic mood stabilization",
    synergyBonus: 79,
  },
  {
    name: "Hexarelin Power",
    peptides: ["hexarelin", "cjc-1295"],
    icon: Rocket,
    color: getSystemColor("growth")!,
    description: "Potent ghrelin-mimetic GH release + sustained GHRH signaling",
    synergyBonus: 85,
  },
  {
    name: "Hexarelin Recovery",
    peptides: ["hexarelin", "bpc-157"],
    icon: Zap,
    color: getSystemColor("healing")!,
    description: "Cardioprotective GH release + tissue healing for athletic recovery",
    synergyBonus: 82,
  },
  {
    name: "IGF Growth Protocol",
    peptides: ["igf-1-lr3", "igf-des", "cjc-1295"],
    icon: Dumbbell,
    color: getSystemColor("growth")!,
    description: "Long-acting IGF-1 + rapid-acting IGF + upstream GH stimulation",
    synergyBonus: 86,
  },
  {
    name: "MGF Extended",
    peptides: ["mgf", "peg-mgf"],
    icon: Dumbbell,
    color: getSystemColor("growth")!,
    description: "Immediate mechano growth factor + PEGylated extended-release MGF",
    synergyBonus: 82,
  },
  {
    name: "Hormonal Restart",
    peptides: ["triptorelin", "gonadorelin"],
    icon: RefreshCw,
    color: getSystemColor("hormonal")!,
    description: "GnRH agonist hormonal reset + pulsatile GnRH maintenance",
    synergyBonus: 83,
  },
  {
    name: "HPG Axis Modulation Stack",
    peptides: ["triptorelin", "enclomiphene"],
    icon: Target,
    color: getSystemColor("hormonal")!,
    description: "GnRH agonist + ERα-antagonist SERM dual-entry HPG axis research model",
    synergyBonus: 85,
    detailPageId: "triptorelin-enclomiphene-hpg-axis",
  },
  {
    name: "VIP Gut-Brain",
    peptides: ["vip", "bpc-157"],
    icon: Pill,
    color: getSystemColor("gut")!,
    description: "Vasoactive intestinal peptide + gut healing for GI-neurological axis",
    synergyBonus: 82,
  },
  {
    name: "VIP Immune",
    peptides: ["vip", "thymosin-alpha-1"],
    icon: Shield,
    color: getSystemColor("immune")!,
    description: "Anti-inflammatory neuropeptide + immune system modulator",
    synergyBonus: 80,
  },
  {
    name: "Ultimate Anti-Aging Skin",
    peptides: ["snap-8", "ghk-cu", "glow-peptide-complex"],
    icon: Sparkles,
    color: getSystemColor("skin")!,
    description: "Wrinkle relaxation + collagen remodeling + radiance complex",
    synergyBonus: 85,
  },
  {
    name: "Cagrilintide Metabolic",
    peptides: ["cagrilintide", "tesamorelin"],
    icon: Target,
    color: getSystemColor("metabolic")!,
    description: "Long-acting amylin analog + visceral fat-targeting GH release",
    synergyBonus: 83,
  },
  {
    name: "REV-ERB Endurance",
    peptides: ["slu-pp-332", "mots-c"],
    icon: Wind,
    color: getSystemColor("energy")!,
    description: "REV-ERB nuclear receptor agonist + mitochondrial-derived metabolic peptide",
    synergyBonus: 83,
  },
  {
    name: "Mazdutide Duo",
    peptides: ["mazdutide", "tesamorelin"],
    icon: Flame,
    color: getSystemColor("metabolic")!,
    description: "Dual metabolic receptor agonist + GHRH visceral fat reduction",
    synergyBonus: 82,
  },
  {
    name: "Adipotide Research",
    peptides: ["adipotide", "5-amino-1mq"],
    icon: Crosshair,
    color: getSystemColor("metabolic")!,
    description: "Fat vasculature disruption + NNMT enzyme inhibition",
    synergyBonus: 79,
  },
  {
    name: "Pinealon Focus",
    peptides: ["pinealon", "semax"],
    icon: Eye,
    color: getSystemColor("cognitive")!,
    description: "Pineal neuropeptide + BDNF-enhancing nootropic",
    synergyBonus: 81,
  },
  {
    name: "AOD Fat Stack",
    peptides: ["aod-9604", "tesamorelin", "5-amino-1mq"],
    icon: Flame,
    color: getSystemColor("metabolic")!,
    description: "HGH fragment + visceral fat GHRH + NNMT inhibition triple approach",
    synergyBonus: 85,
  },
  {
    name: "AICAR Metabolic",
    peptides: ["aicar", "5-amino-1mq"],
    icon: Activity,
    color: getSystemColor("metabolic")!,
    description: "AMPK direct activator + NNMT enzyme inhibitor for metabolic reprogramming",
    synergyBonus: 82,
  },
  {
    name: "GHRP-6 Amplifier",
    peptides: ["ghrp-6", "cjc-1295"],
    icon: Rocket,
    color: getSystemColor("growth")!,
    description: "Hunger-driven GH release + sustained GHRH for powerful growth hormone output",
    synergyBonus: 86,
  },
  {
    name: "IGF Precision",
    peptides: ["igf-des", "mgf"],
    icon: Crosshair,
    color: getSystemColor("growth")!,
    description: "Rapid-acting truncated IGF-1 + mechano growth factor for localized muscle signaling",
    synergyBonus: 83,
  },
  {
    name: "KLOW Hair Restore",
    peptides: ["klow-peptide-complex", "glow-peptide-complex"],
    icon: Sun,
    color: getSystemColor("skin")!,
    description: "Keratin-targeted hair peptide + skin radiance complex for integumentary renewal",
    synergyBonus: 79,
  },
  {
    name: "Oxytocin Wellness",
    peptides: ["oxytocin", "bpc-157"],
    icon: Heart,
    color: getSystemColor("mood")!,
    description: "Social bonding neuropeptide + tissue healing for stress-related gut-brain support",
    synergyBonus: 78,
  },
  {
    name: "NAD+ Mito Stack",
    peptides: ["nad-precursor", "ss-31"],
    icon: Zap,
    color: getSystemColor("energy")!,
    description: "NAD+ fuels sirtuin-dependent mitochondrial enzymes while SS-31 stabilizes cardiolipin membrane structure — metabolic fuel + structural protection",
    synergyBonus: 86,
  },
  {
    name: "Cellular Longevity",
    peptides: ["nad-precursor", "epithalon"],
    icon: Crown,
    color: getSystemColor("longevity")!,
    description: "NAD+/sirtuin DNA repair pathways + telomerase activation — two foundational anti-aging mechanisms working in parallel",
    synergyBonus: 85,
  },
  {
    name: "NAD+ Energy",
    peptides: ["nad-precursor", "mots-c"],
    icon: Activity,
    color: getSystemColor("energy")!,
    description: "NAD+ powers existing mitochondrial enzymes while MOTS-C activates AMPK to build new mitochondria — fuel supply + biogenesis",
    synergyBonus: 84,
  },
  {
    name: "Cellular Defense",
    peptides: ["nad-precursor", "glutathione"],
    icon: Shield,
    color: getSystemColor("immune")!,
    description: "NAD+ supports energy metabolism and sirtuin repair while Glutathione neutralizes the ROS generated — essential energy + antioxidant pairing",
    synergyBonus: 83,
  },
  {
    name: "GLP-1 Metabolic",
    peptides: ["rr-a1", "bpc-157"],
    icon: RefreshCw,
    color: getSystemColor("metabolic")!,
    description: "Single GLP-1 receptor agonism + gut cytoprotection for metabolic research",
    synergyBonus: 86,
  },
  {
    name: "Dual Agonist Stack",
    peptides: ["rr-a2", "bpc-157"],
    icon: Target,
    color: getSystemColor("metabolic")!,
    description: "Dual GLP-1/GIP receptor agonism + gut healing support for metabolic research",
    synergyBonus: 87,
  },
  {
    name: "RR Complete",
    peptides: ["rr-a1", "rr-a3"],
    icon: Crown,
    color: getSystemColor("metabolic")!,
    description: "Single + triple receptor agonists for comprehensive metabolic pathway research",
    synergyBonus: 83,
  },
  {
    name: "Dual Fat Loss",
    peptides: ["rr-a2", "aod-9604"],
    icon: Flame,
    color: getSystemColor("metabolic")!,
    description: "Dual receptor metabolic agonist + HGH fragment lipolysis",
    synergyBonus: 84,
  },
  {
    name: "Weight Management",
    peptides: ["cagrilintide", "rr-a1"],
    icon: Target,
    color: getSystemColor("metabolic")!,
    description: "Amylin analog appetite control + single GLP-1 receptor agonist",
    synergyBonus: 85,
  },
];

export const PEPTIDE_PATHWAYS: Record<string, PeptidePathway> = {
  "bpc-157": {
    name: "BPC-157",
    pathways: ["Nitric Oxide", "Angiogenesis", "Collagen Synthesis"],
    mechanisms: ["VEGF upregulation", "GH receptor activation", "Cytoprotection"],
    systems: ["Healing", "Gut", "Joints"],
  },
  "tb-500": {
    name: "TB-500",
    pathways: ["Actin Regulation", "Angiogenesis", "Cell Migration"],
    mechanisms: ["Thymosin Beta-4 fragment", "Blood vessel formation", "Tissue repair"],
    systems: ["Healing", "Muscle", "Heart"],
  },
  "ghk-cu": {
    name: "GHK-Cu",
    pathways: ["Collagen Synthesis", "Copper Signaling", "Matrix Remodeling"],
    mechanisms: ["TGF-β modulation", "Elastin production", "Wound healing"],
    systems: ["Skin", "Hair", "Longevity"],
  },
  "mots-c": {
    name: "MOTS-C",
    pathways: ["AMPK Activation", "Mitochondrial Biogenesis"],
    mechanisms: ["PGC-1α pathway", "Metabolic regulation", "Energy production"],
    systems: ["Metabolic", "Energy", "Longevity"],
  },
  "rr-a1": {
    name: "RR-A1",
    pathways: ["Incretin", "GLP-1"],
    mechanisms: ["GLP-1 receptor agonist", "Glucose metabolism", "Appetite regulation"],
    systems: ["Metabolic", "Weight", "Fat Loss"],
  },
  "rr-a2": {
    name: "RR-A2",
    pathways: ["Incretin", "GIP", "GLP-1"],
    mechanisms: ["Dual receptor agonist", "Enhanced insulin sensitivity", "Lipid metabolism"],
    systems: ["Metabolic", "Weight", "Fat Loss"],
  },
  "rr-a3": {
    name: "RR-A3",
    pathways: ["Incretin", "GIP", "Glucagon"],
    mechanisms: ["Triple receptor agonist", "Insulin sensitivity", "Fat oxidation"],
    systems: ["Metabolic", "Weight", "Fat Loss"],
  },
  "ipamorelin": {
    name: "Ipamorelin",
    pathways: ["GHRP", "Ghrelin Receptor"],
    mechanisms: ["Selective GH release", "No cortisol spike", "Appetite neutral"],
    systems: ["Growth", "Recovery", "Sleep"],
  },
  "cjc-1295": {
    name: "CJC-1295",
    pathways: ["GHRH", "GH Axis"],
    mechanisms: ["Extended GH pulses", "IGF-1 elevation", "DAC stabilization"],
    systems: ["Growth", "Recovery", "Metabolic"],
  },
  "epithalon": {
    name: "Epithalon",
    pathways: ["Telomerase", "Pineal Gland"],
    mechanisms: ["Telomere elongation", "Melatonin regulation", "Anti-aging"],
    systems: ["Longevity", "Sleep", "Immunity"],
  },
  "semax": {
    name: "Semax",
    pathways: ["BDNF", "NGF", "ACTH Fragment"],
    mechanisms: ["Neuroprotection", "Cognitive enhancement", "Memory formation"],
    systems: ["Cognitive", "Neuroprotection", "Focus"],
  },
  "selank": {
    name: "Selank",
    pathways: ["GABA", "Tuftsin Analog"],
    mechanisms: ["Anxiolytic", "Immune modulation", "Mood regulation"],
    systems: ["Cognitive", "Mood", "Immunity"],
  },
  "kpv": {
    name: "KPV",
    pathways: ["Alpha-MSH Fragment", "NF-κB Inhibition"],
    mechanisms: ["Potent anti-inflammatory", "Gut barrier repair", "Immune modulation"],
    systems: ["Gut", "Immunity", "Healing"],
  },
  "dsip": {
    name: "DSIP",
    pathways: ["Delta Sleep", "Hypothalamus"],
    mechanisms: ["Sleep induction", "Stress modulation", "Circadian regulation"],
    systems: ["Sleep", "Recovery", "Mood"],
  },
  "tesamorelin": {
    name: "Tesamorelin",
    pathways: ["GHRH Analog", "GH Axis"],
    mechanisms: ["Targeted visceral fat reduction", "GH release", "Lipodystrophy treatment"],
    systems: ["Metabolic", "Fat Loss", "Growth"],
  },
  "thymalin": {
    name: "Thymalin",
    pathways: ["Thymus", "Immune Restoration"],
    mechanisms: ["T-cell maturation", "Immune reconstitution", "Thymic regeneration"],
    systems: ["Immunity", "Longevity", "Recovery"],
  },
  "5-amino-1mq": {
    name: "5-Amino-1MQ",
    pathways: ["NNMT Inhibition", "NAD+ Metabolism"],
    mechanisms: ["NNMT enzyme blockade", "SAM conservation", "Fat cell energy shift"],
    systems: ["Metabolic", "Fat Loss", "Energy"],
  },
  "ace-031": {
    name: "ACE-031",
    pathways: ["ActRIIB Decoy", "Myostatin Inhibition"],
    mechanisms: ["Activin/myostatin trapping", "Follistatin-like action", "Muscle anabolism"],
    systems: ["Muscle", "Growth", "Recovery"],
  },
  "aicar": {
    name: "AICAR",
    pathways: ["AMPK Activation", "Metabolic Signaling"],
    mechanisms: ["Direct AMPK phosphorylation", "Exercise mimicry", "Glucose uptake"],
    systems: ["Metabolic", "Energy", "Fat Loss"],
  },
  "aod-9604": {
    name: "AOD-9604",
    pathways: ["GH Fragment", "Lipolysis"],
    mechanisms: ["Beta-3 adrenergic stimulation", "Fat cell apoptosis", "No IGF-1 increase"],
    systems: ["Fat Loss", "Metabolic", "Weight"],
  },
  "adipotide": {
    name: "Adipotide",
    pathways: ["PROHIBITIN Targeting", "Vascular Disruption"],
    mechanisms: ["Fat vasculature apoptosis", "White adipose targeting", "Blood vessel disruption"],
    systems: ["Fat Loss", "Weight", "Metabolic"],
  },
  "cagrilintide": {
    name: "Cagrilintide",
    pathways: ["Amylin Receptor", "Satiety Signaling"],
    mechanisms: ["Long-acting amylin analog", "Appetite suppression", "Gastric emptying delay"],
    systems: ["Weight", "Metabolic", "Fat Loss"],
  },
  "cerebrolysin": {
    name: "Cerebrolysin",
    pathways: ["Neurotrophic Factors", "BDNF/NGF"],
    mechanisms: ["Multi-peptide neurotrophic mix", "Synaptic plasticity", "Neuronal survival"],
    systems: ["Cognitive", "Neuroprotection", "Recovery"],
  },
  "foxo4-dri": {
    name: "FOXO4-DRI",
    pathways: ["FOXO4/p53 Disruption", "Senolysis"],
    mechanisms: ["Senescent cell apoptosis", "p53 nuclear exclusion", "Cellular clearance"],
    systems: ["Longevity", "Anti-Aging", "Recovery"],
  },
  "ghrp-2": {
    name: "GHRP-2",
    pathways: ["GHRP", "Ghrelin Receptor"],
    mechanisms: ["Potent GH release", "Appetite stimulation", "Cortisol modulation"],
    systems: ["Growth", "Recovery", "Muscle"],
  },
  "ghrp-6": {
    name: "GHRP-6",
    pathways: ["GHRP", "Ghrelin Receptor"],
    mechanisms: ["Strong GH release", "Hunger stimulation", "IGF-1 elevation"],
    systems: ["Growth", "Muscle", "Recovery"],
  },
  "glow-peptide-complex": {
    name: "GLOW Peptide Complex",
    pathways: ["Collagen Synthesis", "Melanin Regulation"],
    mechanisms: ["Skin radiance enhancement", "Antioxidant protection", "Hydration support"],
    systems: ["Skin", "Anti-Aging", "Hair"],
  },
  "glutathione": {
    name: "Glutathione",
    pathways: ["GSH Redox Cycle", "Phase II Detoxification"],
    mechanisms: ["Master antioxidant", "Free radical neutralization", "Liver detoxification"],
    systems: ["Immunity", "Skin", "Longevity"],
  },
  "gonadorelin": {
    name: "Gonadorelin",
    pathways: ["GnRH", "HPG Axis"],
    mechanisms: ["Pulsatile LH/FSH release", "Gonadotropin stimulation", "Fertility support"],
    systems: ["Hormonal", "Fertility", "Recovery"],
  },
  "hexarelin": {
    name: "Hexarelin",
    pathways: ["GHRP", "Ghrelin Receptor"],
    mechanisms: ["Strong GH secretagogue", "Cardioprotective effects", "IGF-1 stimulation"],
    systems: ["Growth", "Heart", "Recovery"],
  },
  "igf-1-lr3": {
    name: "IGF-1 LR3",
    pathways: ["IGF-1 Receptor", "PI3K/Akt"],
    mechanisms: ["Extended IGF-1 signaling", "Protein synthesis", "Cell proliferation"],
    systems: ["Muscle", "Growth", "Recovery"],
  },
  "igf-des": {
    name: "IGF-DES",
    pathways: ["IGF-1 Receptor", "Truncated IGF-1"],
    mechanisms: ["Rapid IGF-1 action", "Enhanced bioavailability", "Local tissue growth"],
    systems: ["Muscle", "Growth", "Recovery"],
  },
  "klow-peptide-complex": {
    name: "KLOW Peptide Complex",
    pathways: ["Keratin Synthesis", "Growth Factor Signaling"],
    mechanisms: ["Hair follicle stimulation", "Scalp nourishment", "Keratinocyte activation"],
    systems: ["Hair", "Skin", "Anti-Aging"],
  },
  "kisspeptin-10": {
    name: "Kisspeptin-10",
    pathways: ["Kisspeptin/GPR54", "GnRH Stimulation"],
    mechanisms: ["GnRH neuron activation", "LH surge triggering", "Reproductive signaling"],
    systems: ["Fertility", "Hormonal", "Sexual Health"],
  },
  "ll-37": {
    name: "LL-37",
    pathways: ["Cathelicidin", "Innate Immunity"],
    mechanisms: ["Antimicrobial membrane disruption", "Immune cell recruitment", "Biofilm disruption"],
    systems: ["Immunity", "Healing", "Gut"],
  },
  "mgf": {
    name: "MGF",
    pathways: ["IGF-1 Splice Variant", "Mechano-Growth"],
    mechanisms: ["Satellite cell activation", "Local muscle repair", "Myoblast proliferation"],
    systems: ["Muscle", "Recovery", "Growth"],
  },
  "mazdutide": {
    name: "Mazdutide",
    pathways: ["Incretin", "Glucagon"],
    mechanisms: ["Dual receptor agonist", "Appetite reduction", "Hepatic fat oxidation"],
    systems: ["Weight", "Metabolic", "Fat Loss"],
  },
  "melanotan-i": {
    name: "Melanotan I",
    pathways: ["MC1R", "Melanogenesis"],
    mechanisms: ["Selective melanocortin-1 agonist", "Eumelanin production", "UV protection"],
    systems: ["Skin", "Anti-Aging", "Immunity"],
  },
  "melanotan-ii": {
    name: "Melanotan II",
    pathways: ["MC1R/MC4R", "Melanogenesis"],
    mechanisms: ["Non-selective melanocortin agonist", "Tanning response", "Libido enhancement"],
    systems: ["Skin", "Sexual Health", "Fat Loss"],
  },
  "nad-precursor": {
    name: "NAD+ Precursor",
    pathways: ["NAD+ Salvage", "Sirtuin Activation", "PARP DNA Repair"],
    mechanisms: ["NAD+ level restoration", "Sirtuin-dependent DNA repair", "Mitochondrial enzyme support"],
    systems: ["Longevity", "Metabolic", "Recovery"],
  },
  "oxytocin": {
    name: "Oxytocin",
    pathways: ["Oxytocin Receptor", "Hypothalamic"],
    mechanisms: ["Social bonding", "Uterine contraction", "Anxiolytic effects"],
    systems: ["Mood", "Hormonal", "Recovery"],
  },
  "peg-mgf": {
    name: "PEG-MGF",
    pathways: ["IGF-1 Splice Variant", "PEGylated Delivery"],
    mechanisms: ["Extended mechano growth signaling", "Systemic muscle repair", "Satellite cell recruitment"],
    systems: ["Muscle", "Recovery", "Growth"],
  },
  "pt-141": {
    name: "PT-141",
    pathways: ["MC4R", "Melanocortin"],
    mechanisms: ["Central nervous system arousal", "Dopaminergic pathway", "Sexual desire activation"],
    systems: ["Sexual Health", "Mood", "Hormonal"],
  },
  "pinealon": {
    name: "Pinealon",
    pathways: ["Pineal Gland", "Neuropeptide Regulation"],
    mechanisms: ["Pinealocyte gene regulation", "Neuroprotection", "Circadian modulation"],
    systems: ["Sleep", "Cognitive", "Neuroprotection"],
  },
  "slu-pp-332": {
    name: "SLU-PP-332",
    pathways: ["REV-ERB Agonist", "Nuclear Receptor"],
    mechanisms: ["Circadian clock modulation", "Exercise gene expression", "Mitochondrial biogenesis"],
    systems: ["Energy", "Metabolic", "Muscle"],
  },
  "ss-31": {
    name: "SS-31",
    pathways: ["Cardiolipin Binding", "Mitochondrial Inner Membrane"],
    mechanisms: ["Electron transport stabilization", "ROS reduction", "ATP production enhancement"],
    systems: ["Energy", "Heart", "Longevity"],
  },
  "sermorelin": {
    name: "Sermorelin",
    pathways: ["GHRH", "GH Axis"],
    mechanisms: ["Natural GHRH analog", "Pulsatile GH release", "IGF-1 stimulation"],
    systems: ["Growth", "Recovery", "Sleep"],
  },
  "snap-8": {
    name: "Snap-8",
    pathways: ["SNARE Complex Inhibition", "Acetylcholine Modulation"],
    mechanisms: ["Neuromuscular signal reduction", "Wrinkle relaxation", "Expression line softening"],
    systems: ["Skin", "Anti-Aging", "Muscle"],
  },
  "survodutide": {
    name: "Survodutide",
    pathways: ["Incretin", "Glucagon"],
    mechanisms: ["Dual incretin agonist", "Energy expenditure increase", "Liver fat reduction"],
    systems: ["Weight", "Metabolic", "Fat Loss"],
  },
  "thymosin-alpha-1": {
    name: "Thymosin Alpha-1",
    pathways: ["Thymus", "TLR Signaling"],
    mechanisms: ["Dendritic cell maturation", "NK cell activation", "Immune surveillance"],
    systems: ["Immunity", "Longevity", "Recovery"],
  },
  "triptorelin": {
    name: "Triptorelin",
    pathways: ["GnRH Agonist", "HPG Axis"],
    mechanisms: ["Initial LH/FSH surge", "Subsequent receptor desensitization", "Hormonal reset"],
    systems: ["Hormonal", "Fertility", "Recovery"],
  },
  "vip": {
    name: "VIP",
    pathways: ["VPAC1/VPAC2", "Neuropeptide"],
    mechanisms: ["Vasodilation", "Anti-inflammatory", "Smooth muscle relaxation"],
    systems: ["Gut", "Immunity", "Neuroprotection"],
  },
};

export function normalizePeptideName(name: string): string {
  return name.toLowerCase()
    .replace(/[^a-z0-9]/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .replace(/\s*\(.*?\)\s*/g, '');
}

export function getSynergyPartners(peptideName: string): { partner: string; stack: KnownStack; synergyBonus: number }[] {
  const normalizedName = normalizePeptideName(peptideName);

  const knownAliases: Record<string, string> = {
    "cjc-1295-no-dac": "cjc-1295",
    "cjc-1295-w-dac": "cjc-1295",
    "cjc-1295-with-dac": "cjc-1295",
  };
  const resolvedName = knownAliases[normalizedName] || normalizedName;

  const partners: { partner: string; stack: KnownStack; synergyBonus: number }[] = [];

  for (const stack of KNOWN_STACKS) {
    if (stack.peptides.includes(resolvedName)) {
      for (const p of stack.peptides) {
        if (p !== resolvedName) {
          partners.push({
            partner: PEPTIDE_PATHWAYS[p]?.name || p.split("-").map(w => w.charAt(0).toUpperCase() + w.slice(1)).join("-"),
            stack,
            synergyBonus: stack.synergyBonus,
          });
        }
      }
    }
  }

  const uniquePartners = partners.reduce((acc, curr) => {
    const existing = acc.find(p => p.partner === curr.partner);
    if (!existing || existing.synergyBonus < curr.synergyBonus) {
      return [...acc.filter(p => p.partner !== curr.partner), curr];
    }
    return acc;
  }, [] as typeof partners);

  uniquePartners.sort((a, b) => b.synergyBonus - a.synergyBonus);

  return uniquePartners.slice(0, 3);
}
