import { motion, useInView } from "framer-motion";
import { useRef, useState, useEffect } from "react";
import { Shield, RefreshCw, Zap, AlertTriangle, Check } from "lucide-react";
import { useHoverCapable } from "@/hooks/use-hover-capable";

interface RedoxPhase {
  id: number;
  label: string;
  color: string;
  icon: typeof Shield;
  description: string;
}

const redoxPhases: RedoxPhase[] = [
  { id: 0, label: "ROS Attack", icon: AlertTriangle, color: "#ef4444", description: "Reactive oxygen species threaten cellular components" },
  { id: 1, label: "GSH Defense", icon: Shield, color: "#E7FB10", description: "Reduced glutathione (GSH) donates electrons to neutralize ROS" },
  { id: 2, label: "GSSG Formed", icon: RefreshCw, color: "#21d8ff", description: "Oxidized glutathione (GSSG) formed; ready for recycling" },
  { id: 3, label: "Cell Protected", icon: Check, color: "#10b981", description: "Cellular components protected; GSH regenerated by reductase" },
];

function RedoxCycleAnimation({ isInView, activePhase }: { isInView: boolean; activePhase: number }) {
  return (
    <div className="relative w-full h-56 flex items-center justify-center overflow-hidden">
      <div 
        className="absolute inset-0 rounded-xl"
        style={{
          background: 'radial-gradient(ellipse at center, rgba(231, 251, 16, 0.1) 0%, transparent 70%)'
        }}
      />
      
      <svg viewBox="0 0 400 220" className="w-full h-full max-w-lg">
        <defs>
          <filter id="gshGlow">
            <feGaussianBlur stdDeviation="3" result="coloredBlur"/>
            <feMerge>
              <feMergeNode in="coloredBlur"/>
              <feMergeNode in="SourceGraphic"/>
            </feMerge>
          </filter>
        </defs>

        <motion.circle
          cx="200" cy="110" r="50"
          fill="rgba(33, 216, 255, 0.08)"
          stroke="rgba(33, 216, 255, 0.3)"
          strokeWidth="1"
          strokeDasharray="8,4"
          initial={{ opacity: 0 }}
          animate={isInView ? { opacity: 1 } : {}}
        />
        <motion.text x="200" y="115" textAnchor="middle" fill="currentColor" fillOpacity="0.4" fontSize="8"
          initial={{ opacity: 0 }}
          animate={isInView ? { opacity: 1 } : {}}
        >
          CELL
        </motion.text>

        {activePhase === 0 && [0, 1, 2, 3, 4].map((i) => (
          <motion.g key={`ros-${i}`}>
            <motion.circle
              r="8"
              fill="rgba(239, 68, 68, 0.3)"
              stroke="#ef4444"
              strokeWidth="2"
              initial={{ opacity: 0, cx: 50 + i * 20, cy: 40 + i * 15 }}
              animate={isInView ? {
                cx: [50 + i * 20, 150 + (i % 3) * 30],
                cy: [40 + i * 15, 90 + (i % 2) * 30],
                opacity: [0, 1, 1],
                scale: [0.5, 1, 1.2]
              } : {}}
              transition={{
                duration: 2,
                delay: i * 0.2,
                repeat: Infinity,
                repeatType: "reverse"
              }}
              filter="url(#gshGlow)"
            />
            <motion.text
              fontSize="6" fill="#ef4444" fontWeight="bold"
              initial={{ opacity: 0 }}
              animate={isInView ? { opacity: 1 } : {}}
              transition={{ delay: 0.5 + i * 0.2 }}
            >
              <animateMotion dur="2s" repeatCount="indefinite">
                <mpath href={`#rosPath${i}`} />
              </animateMotion>
              ROS
            </motion.text>
          </motion.g>
        ))}

        <motion.g>
          <motion.circle
            cx="120" cy="110" r="25"
            fill={activePhase >= 1 ? "rgba(231, 251, 16, 0.25)" : "rgba(231, 251, 16, 0.1)"}
            stroke="#E7FB10"
            strokeWidth={activePhase >= 1 ? 3 : 2}
            initial={{ scale: 0 }}
            animate={isInView ? { 
              scale: activePhase === 1 ? [1, 1.15, 1] : 1
            } : {}}
            transition={{ duration: 1.5, repeat: activePhase === 1 ? Infinity : 0 }}
            filter={activePhase >= 1 ? "url(#gshGlow)" : undefined}
            style={activePhase >= 1 ? { filter: 'drop-shadow(0 0 10px rgba(231, 251, 16, 0.6))' } : {}}
          />
          <motion.text x="120" y="107" textAnchor="middle" fill="#E7FB10" fontSize="12" fontWeight="bold"
            initial={{ opacity: 0 }}
            animate={isInView ? { opacity: 1 } : {}}
          >
            GSH
          </motion.text>
          <motion.text x="120" y="120" textAnchor="middle" fill="rgba(231, 251, 16, 0.7)" fontSize="7"
            initial={{ opacity: 0 }}
            animate={isInView ? { opacity: 1 } : {}}
          >
            (Reduced)
          </motion.text>
        </motion.g>

        <motion.g>
          <motion.circle
            cx="280" cy="110" r="25"
            fill={activePhase >= 2 ? "rgba(33, 216, 255, 0.25)" : "rgba(33, 216, 255, 0.1)"}
            stroke="#21d8ff"
            strokeWidth={activePhase >= 2 ? 3 : 2}
            initial={{ scale: 0 }}
            animate={isInView ? { 
              scale: activePhase === 2 ? [1, 1.1, 1] : 1
            } : {}}
            transition={{ duration: 1.5, repeat: activePhase === 2 ? Infinity : 0 }}
            filter={activePhase >= 2 ? "url(#gshGlow)" : undefined}
          />
          <motion.text x="280" y="107" textAnchor="middle" fill="#21d8ff" fontSize="12" fontWeight="bold"
            initial={{ opacity: 0 }}
            animate={isInView ? { opacity: 1 } : {}}
          >
            GSSG
          </motion.text>
          <motion.text x="280" y="120" textAnchor="middle" fill="rgba(33, 216, 255, 0.7)" fontSize="7"
            initial={{ opacity: 0 }}
            animate={isInView ? { opacity: 1 } : {}}
          >
            (Oxidized)
          </motion.text>
        </motion.g>

        {activePhase >= 1 && (
          <motion.g>
            <motion.path
              d="M 148 100 Q 200 70 252 100"
              stroke="#E7FB10"
              strokeWidth="2"
              fill="none"
              initial={{ pathLength: 0 }}
              animate={isInView ? { pathLength: 1 } : {}}
              transition={{ duration: 0.8, delay: 0.3 }}
            />
            <motion.polygon
              points="248,95 258,100 248,105"
              fill="#E7FB10"
              initial={{ opacity: 0 }}
              animate={isInView ? { opacity: 1 } : {}}
              transition={{ delay: 1.1 }}
            />
            <motion.text x="200" y="60" textAnchor="middle" fill="#E7FB10" fontSize="8" fontWeight="bold"
              initial={{ opacity: 0 }}
              animate={isInView && activePhase >= 1 ? { opacity: 1 } : {}}
            >
              e⁻ donation → ROS neutralized
            </motion.text>
          </motion.g>
        )}

        {activePhase >= 3 && (
          <motion.g>
            <motion.path
              d="M 252 120 Q 200 150 148 120"
              stroke="#10b981"
              strokeWidth="2"
              fill="none"
              initial={{ pathLength: 0 }}
              animate={isInView ? { pathLength: 1 } : {}}
              transition={{ duration: 0.8, delay: 0.5 }}
            />
            <motion.polygon
              points="152,115 142,120 152,125"
              fill="#10b981"
              initial={{ opacity: 0 }}
              animate={isInView ? { opacity: 1 } : {}}
              transition={{ delay: 1.3 }}
            />
            <motion.text x="200" y="165" textAnchor="middle" fill="#10b981" fontSize="8" fontWeight="bold"
              initial={{ opacity: 0 }}
              animate={isInView && activePhase >= 3 ? { opacity: 1 } : {}}
            >
              Glutathione Reductase + NADPH
            </motion.text>
          </motion.g>
        )}

        {activePhase >= 1 && [0, 1].map((i) => (
          <motion.circle
            key={`electron-${i}`}
            r="4"
            fill="#E7FB10"
            initial={{ opacity: 0 }}
            animate={{
              cx: [148, 180, 210, 248],
              cy: [100, 75 + i * 10, 75 + i * 10, 100],
              opacity: [0, 1, 1, 0],
            }}
            transition={{
              duration: 1.5,
              delay: 0.5 + i * 0.3,
              repeat: activePhase === 1 ? Infinity : 0,
              ease: "easeInOut"
            }}
            style={{ filter: 'drop-shadow(0 0 6px rgba(231, 251, 16, 0.8))' }}
          />
        ))}

        {activePhase >= 3 && (
          <motion.g>
            <motion.rect
              x="175" y="182" width="50" height="20" rx="4"
              fill="rgba(16, 185, 129, 0.2)"
              stroke="#10b981"
              strokeWidth="1.5"
              initial={{ opacity: 0, scale: 0.8 }}
              animate={isInView ? { opacity: 1, scale: 1 } : {}}
              transition={{ delay: 1.5 }}
            />
            <motion.text x="200" y="196" textAnchor="middle" fill="#10b981" fontSize="8" fontWeight="bold"
              initial={{ opacity: 0 }}
              animate={isInView ? { opacity: 1 } : {}}
              transition={{ delay: 1.6 }}
            >
              PROTECTED
            </motion.text>
          </motion.g>
        )}

        <motion.text
          x="200" y="215"
          textAnchor="middle"
          fill="currentColor" fillOpacity="0.6"
          fontSize="9"
          initial={{ opacity: 0 }}
          animate={isInView ? { opacity: 1 } : {}}
          transition={{ delay: 2 }}
        >
          GSH/GSSG Ratio: Key Indicator of Cellular Redox Status
        </motion.text>
      </svg>
    </div>
  );
}

export function GlutathioneRedoxVisual() {
  const containerRef = useRef<HTMLDivElement>(null);
  const isInView = useInView(containerRef, { once: true, margin: "-50px" });
  const hoverCapable = useHoverCapable();
  const [activePhase, setActivePhase] = useState(0);
  const [isPlaying, setIsPlaying] = useState(true);

  useEffect(() => {
    if (!isPlaying || !isInView) return;
    
    const interval = setInterval(() => {
      setActivePhase((prev) => (prev + 1) % redoxPhases.length);
    }, 2800);
    
    return () => clearInterval(interval);
  }, [isPlaying, isInView]);

  return (
    <div ref={containerRef} className="relative">
      <div 
        className="absolute inset-0 h-full w-full rounded-2xl blur-3xl -z-10"
        style={{
          background: 'radial-gradient(ellipse at center, rgba(231, 251, 16, 0.08) 0%, transparent 70%)'
        }}
      />
      
      <motion.div
        className="text-center mb-6"
        initial={{ opacity: 0, y: 20 }}
        animate={isInView ? { opacity: 1, y: 0 } : {}}
      >
        <div 
          className="inline-flex items-center gap-2 px-4 py-2 rounded-full border mb-4"
          style={{
            background: 'linear-gradient(135deg, rgba(231, 251, 16, 0.15) 0%, rgba(16, 185, 129, 0.05) 100%)',
            borderColor: '#E7FB10',
            boxShadow: '0 0 20px rgba(231, 251, 16, 0.3)'
          }}
        >
          <Shield className="h-5 w-5 text-[#E7FB10]" style={{ filter: 'drop-shadow(0 0 4px rgba(231, 251, 16, 0.6))' }} />
          <span className="text-sm font-bold bg-gradient-to-r from-[#E7FB10] to-[#10b981] bg-clip-text text-transparent">
            GSH/GSSG Redox Cycle
          </span>
        </div>
        <p className="text-sm text-muted-foreground max-w-md mx-auto">
          How glutathione protects cells from oxidative damage through redox cycling
        </p>
      </motion.div>

      <div 
        className="rounded-xl border p-6 mb-6"
        style={{ 
          borderColor: 'rgba(231, 251, 16, 0.3)',
          background: 'linear-gradient(135deg, rgba(231, 251, 16, 0.05) 0%, transparent 50%)'
        }}
      >
        <RedoxCycleAnimation isInView={isInView} activePhase={activePhase} />
        
        <div className="mt-6">
          <div className="flex items-center justify-between mb-4">
            <span className="text-xs text-muted-foreground uppercase tracking-wider">
              Antioxidant Cycle
            </span>
            <button
              onClick={() => setIsPlaying(!isPlaying)}
              className="text-xs px-3 py-1 rounded-full transition-all"
              style={{
                backgroundColor: isPlaying ? 'rgba(231, 251, 16, 0.2)' : 'hsl(var(--foreground) / 0.1)',
                color: isPlaying ? '#E7FB10' : 'hsl(var(--foreground) / 0.5)',
                border: `1px solid ${isPlaying ? 'rgba(231, 251, 16, 0.4)' : 'hsl(var(--foreground) / 0.1)'}`
              }}
              data-testid="button-toggle-animation"
            >
              {isPlaying ? '⏸ Pause' : '▶ Play'}
            </button>
          </div>
          
          <div className="grid grid-cols-4 gap-2">
            {redoxPhases.map((phase) => {
              const Icon = phase.icon;
              const isActive = activePhase === phase.id;
              
              return (
                <motion.button
                  key={phase.id}
                  onClick={() => {
                    setActivePhase(phase.id);
                    setIsPlaying(false);
                  }}
                  className="relative p-3 rounded-lg text-center transition-all cursor-pointer"
                  style={{
                    backgroundColor: isActive ? `${phase.color}20` : 'hsl(var(--foreground) / 0.03)',
                    border: `1.5px solid ${isActive ? phase.color : 'hsl(var(--foreground) / 0.1)'}`,
                    boxShadow: isActive ? `0 0 20px ${phase.color}30` : 'none'
                  }}
                  whileHover={hoverCapable ? { scale: 1.02 } : {}}
                  whileTap={{ scale: 0.98 }}
                  data-testid={`phase-${phase.id}`}
                >
                  <motion.div
                    className="w-8 h-8 rounded-lg mx-auto mb-2 flex items-center justify-center"
                    style={{ backgroundColor: `${phase.color}20` }}
                    animate={isActive ? { scale: [1, 1.1, 1] } : {}}
                    transition={{ duration: 1, repeat: isActive ? Infinity : 0 }}
                  >
                    <Icon className="h-4 w-4" style={{ color: phase.color, filter: `drop-shadow(0 0 4px ${phase.color})` }} />
                  </motion.div>
                  <span className="text-[10px] font-bold block" style={{ color: isActive ? phase.color : 'hsl(var(--foreground) / 0.6)' }}>
                    {phase.label}
                  </span>
                </motion.button>
              );
            })}
          </div>
          
          <motion.div
            key={activePhase}
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            className="mt-4 p-3 rounded-lg text-center"
            style={{
              backgroundColor: `${redoxPhases[activePhase].color}10`,
              border: `1px solid ${redoxPhases[activePhase].color}30`
            }}
          >
            <p className="text-sm text-muted-foreground">
              {redoxPhases[activePhase].description}
            </p>
          </motion.div>
        </div>

        <div className="mt-6 pt-6 border-t" style={{ borderColor: 'hsl(var(--border))' }}>
          <div className="flex items-center gap-2 mb-3">
            <Zap className="h-4 w-4 text-[#21d8ff]" />
            <span className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">
              Cellular Distribution
            </span>
          </div>
          <div className="grid grid-cols-3 gap-2 text-center">
            {[
              { label: "Cytoplasm", value: "0.5-10 mM", pct: "85%" },
              { label: "Mitochondria", value: "10-15%", pct: "Critical" },
              { label: "GSH:GSSG", value: ">90:10", pct: "Healthy" }
            ].map((stat, i) => (
              <motion.div
                key={i}
                className="p-2 rounded-lg"
                style={{ backgroundColor: 'rgba(33, 216, 255, 0.1)', border: '1px solid rgba(33, 216, 255, 0.2)' }}
                initial={{ opacity: 0, y: 10 }}
                animate={isInView ? { opacity: 1, y: 0 } : {}}
                transition={{ delay: 1.5 + i * 0.1 }}
              >
                <div className="text-sm font-bold text-[#21d8ff]">{stat.value}</div>
                <div className="text-[10px] text-muted-foreground">{stat.label}</div>
              </motion.div>
            ))}
          </div>
        </div>
      </div>

      <motion.div
        className="text-center text-xs text-muted-foreground"
        initial={{ opacity: 0 }}
        animate={isInView ? { opacity: 1 } : {}}
        transition={{ delay: 2 }}
      >
        <span className="px-3 py-1 rounded-full bg-muted/30">
          Glutathione redox cycle visualization • For educational purposes only
        </span>
      </motion.div>
    </div>
  );
}
