CREATE TABLE IF NOT EXISTS "research_stacks" (
  "id" text PRIMARY KEY NOT NULL,
  "name" text NOT NULL,
  "subtitle" text DEFAULT '',
  "description" text NOT NULL,
  "long_description" text DEFAULT '',
  "peptide_ids" text[] NOT NULL DEFAULT '{}',
  "peptide_details" jsonb DEFAULT '[]'::jsonb,
  "key_benefits" text[] DEFAULT '{}',
  "research_applications" text[] DEFAULT '{}',
  "synergy_copy" jsonb DEFAULT '{}'::jsonb,
  "storage_guide" text DEFAULT '',
  "education_links" jsonb DEFAULT '[]'::jsonb,
  "icon_name" text DEFAULT 'FlaskConical',
  "color" text DEFAULT '#6366f1',
  "badge" text,
  "badge_color" text,
  "category" text DEFAULT 'Recovery',
  "synergy_bonus" integer DEFAULT 0,
  "detail_page_id" text,
  "show_on_page" boolean DEFAULT false,
  "is_active" boolean DEFAULT true,
  "sort_order" integer DEFAULT 0,
  "created_at" timestamp DEFAULT now()
);
